server {
    listen 80;
    server_name njcb-union-prototype.morningstar369.com;
    root /opt/njcb/union-prototype;

    location /admin {
        try_files /admin.html =404;
    }
    
    location /member-pc {
        try_files /member-pc.html =404;
    }

    location /member-mobile {
        try_files /member-mobile.html =404;
    }
}