logging:
  config: classpath:logback-spring.xml
  file: # handler
    path: ./logs
  pattern: # formatter
    dateformat: yyyy-MM-dd HH:mm:ss.SSS
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN}}){blue} [%thread] %clr([%level]){magenta} %logger{50} - %msg%n"
    file: "%d{${LOG_DATEFORMAT_PATTERN}} [%thread] %-5level %logger{50} - %msg%n"
  level: # logger-level
    root: info
    org.springframework.transaction: debug
    org.springframework.jdbc.datasource.DataSourceTransactionManager: debug
    com.morningstar.practice:
      service: debug
  logback:
    rollingpolicy:
      max-file-size: 50MB
      max-history: 30