server:
  port: 8091
spring:
  application:
    name: 晨星小站
  config:
    import: "optional:classpath:.env[.properties]"
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: GMT+8
    default-property-inclusion: non_null
  main:
    banner-mode: off
  profiles:
    active: @profiles.active@, log, cache, doc, db, jwt, mq, email, qrcode, perm, others, app
#  mvc:
#    static-path-pattern: /static/** # NOTE: 已整合入`WebMvcConfig`