spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: false
morningstar:
  app:
    dev:
      sonarqube:
        token: squ_582d6a8085c8faa67488b29d479b6e14028be4b3
        backend-origin: http://127.0.0.1:7002
        container-origin: http://host.docker.internal:7002
      gitea:
        backend-origin: http://127.0.0.1:7001
        container-origin: http://host.docker.internal:7001
        bot-token: d093b22293b5840087fe574378955b1d20cb3c7c
        admin-token: 4e972cc47581af2bbf41446af53a8d614560904d
  simulation:
    interval: 60
  oauth2:
    github-client-id: Ov23ct1bjDaoSfh9hQLj
    github-client-secret: ${GITHUB_OAUTH_CLIENT_SECRET_DEV}
  email:
    host: 127.0.0.1
    port: 1025
    debug: true
    ssl: false
  mysql:
    host: localhost
    password: 1234asdw
  redis:
    host: 127.0.0.1
    password: ''
  mongodb:
    host: localhost
    password: 1234asdw
  es:
    hostname: "localhost"
    port: 9200
  rabbitmq:
    host: localhost
    password: 1234asdw
  neo4j:
    host: localhost
    password: 1234asdw
  security:
    cors:
      origins: "http://127.0.0.1:8090,http://localhost:8090"
  account:
    user:
      - username: "henry"
        password: "1234asdw"
        nickname: 河海小爬虫
      - username: "sherry"
        password: "123456"
    user-role:
      - username: "henry"
        role-tag: "system_admin"
      - username: "henry"
        role-tag: "blog_admin"
      - username: "henry"
        role-tag: "proxy_admin"
server:
  address: 0.0.0.0