kill:
  love:
    photos:
      - 与人间小苦瓜的合照.jpg
      - 嘴里含着花花.jpg
      - 在窗台旁看书.jpg
      - 坐床上喝瑞辛.png
      - 塞尔达吃牛排但是不高兴.png
      - 头上戴着花花.jpg
      - 很乖的靠着镜子.jpg
      - 我总因不够变态而无法融入你们.jpg
      - 我是小脑斧.jpg
      - 疲惫但优雅.jpg
      - 紫金山的日出.jpg
      - 阳光下的影子.jpg