springdoc:
  api-docs:
    path: /docs/json
  swagger-ui:
    path: /docs/ui
  show-actuator: true
  group-configs:
    - group: "业务接口"
      packages-to-scan:
        - com.morningstar.system.web.controller
        - com.morningstar.blog.web.controller
        - com.morningstar.lab.web.controller
        - com.morningstar.love.web.controller
        - com.morningstar.pic.web.controller
        - com.morningstar.proxy.web.controller
    - group: "系统监控"
      paths-to-match: /actuator/**