export enum ResponseCode {
    SUCCESS = 'SUCCESS',
    TOKEN_INVALID = 'TOKEN_INVALID',
    TOKEN_EXPIRED = 'TOKEN_EXPIRED',
    CHECK_CODE_TIMEOUT = 'CHECK_CODE_TIMEOUT',
    CHECK_CODE_ERROR = 'CHECK_CODE_ERROR',
}
